### ISSUE TITLE
DEV Container missing start-cslang.sh

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/CloudSlang-Docker-Image#11] opened 2016-01-30 12:18 UTC
Hello

start-cslang.sh is missing inside the DEV container automatic build cloudslang/cloudslang-dev

@Bonczidai thanks

**Comment by levice14** [comment] 2016-02-02 10:47
duplicate of #10 , we'll continue there
thanks @mbettan

**Closed as completed** 2016-02-02 10:47 UTC
